<?php

/**
 * @file
 * Install and uninstall functions for the CleanTalk module.
 */

/**
 * Implements hook_install().
 */
function cleantalk_install() 
{  
  db_drop_table('cleantalk_timelabels');
  $cleantalk_timelabels = array(
    'description' => 'Timelabels for admin notification sending.',
    'fields' => array(
      'ct_key' => array(
        'type' => 'varchar',
        'length' => 64,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Notification ID.',
      ),
      'ct_value' => array(
        'type' => 'int',
        'length' => 12,
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Time of last notification.',
      ),
    ),
    'primary key' => array('ct_key'),
  );
  db_create_table('cleantalk_timelabels', $cleantalk_timelabels);

  db_drop_table('cleantalk_sfw');
  $cleantalk_sfw = array(
    'description' => 'SpamFireWall data.',
    'fields' => array(
      'network' => array(
        'type' => 'int',
        'length' => 11,
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Spam network.',
      ),
      'mask' => array(
        'type' => 'int',
        'length' => 11,
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Spam mask.',
      ),
    ),
    'indexes' => array(
      'network'        => array('network'),
      ),
  );
  db_create_table('cleantalk_sfw', $cleantalk_sfw);
  
  db_drop_table('cleantalk_sfw_logs');
    $cleantalk_sfw_logs = array(
    'description' => 'SpamFireWall logs.',
    'fields' => array(
      'ip' => array(
        'type' => 'varchar',
        'length' => 15,
        'not null' => TRUE,
        'default' => '',
        'description' => 'IP.'
      ),
      'all_entries' => array(
        'type' => 'int',
        'description' => 'All entries.'
      ),
    'blocked_entries' => array(
        'type' => 'int',
        'description' => 'Blocked entries.'
      ),
      'entries_timestamp' => array(
        'type' => 'int',
        'description' => 'time().'
      )
    ),
    'primary key' => array('ip'),
  );
  db_create_table('cleantalk_sfw_logs', $cleantalk_sfw_logs);
}
/**
 * Implements hook_uninstall().
 */
function cleantalk_uninstall() {
  variable_del('cleantalk_check_register');
  variable_del('cleantalk_authkey');
  variable_del('cleantalk_check_ccf');
  variable_del('cleantalk_link');
  variable_del('cleantalk_sfw');
  variable_del('cleantalk_check_comments');
  variable_del('cleantalk_check_comments_automod');
  variable_del('cleantalk_check_comments_min_approved');
  variable_del('cleantalk_check_webforms');
  variable_del('cleantalk_check_contact_forms');
  variable_del('cleantalk_check_forum_topics');
  variable_del('cleantalk_work_url');
  variable_del('cleantalk_server_url');
  variable_del('cleantalk_server_ttl');
  variable_del('cleantalk_server_changed');
  variable_del('ct_sfw_last_logs_sent');
  variable_del('ct_sfw_last_updated');
  db_drop_table('cleantalk_timelabels');
  db_drop_table('cleantalk_sfw');
  db_drop_table('cleantalk_sfw_logs');  
}

/**
 * Add new table for SpamFireWall logs
 */
function cleantalk_update_7300(&$sandbox = NULL){
  variable_set('ct_sfw_last_logs_sent', time());
  db_drop_table('cleantalk_sfw_logs');
  $cleantalk_sfw_logs = array(
    'description' => 'Comment checking results - CIDs and server responces.',
    'fields' => array(
      'ip' => array(
        'type' => 'varchar',
        'length' => 15,
        'not null' => TRUE,
        'default' => '',
        'description' => 'IP.'
      ),
      'all' => array(
        'type' => 'int',
        'description' => 'All entries.'
      ),
      'blocked' => array(
        'type' => 'int',
        'description' => 'Blocked entries.'
      ),
      'timestamp' => array(
        'type' => 'int',
        'description' => 'time().'
      )
    ),
    'primary key' => array('ip'),
  );
  db_create_table('cleantalk_sfw_logs', $cleantalk_sfw_logs);
  
  return '* New table for SpamFireWall logs added.';
}

/**
 * Compatibilty changes for SpamFireWall logs table
 */
function cleantalk_update_7301(&$sandbox = NULL){
  variable_set('ct_sfw_last_logs_sent', time());
  db_drop_table('cleantalk_sfw_logs');
  $cleantalk_sfw_logs = array(
    'description' => 'Comment checking results - CIDs and server responces.',
    'fields' => array(
      'ip' => array(
        'type' => 'varchar',
        'length' => 15,
        'not null' => TRUE,
        'default' => '',
        'description' => 'IP.'
      ),
      'all_entries' => array(
        'type' => 'int',
        'description' => 'All entries.'
      ),
      'blocked_entries' => array(
        'type' => 'int',
        'description' => 'Blocked entries.'
      ),
      'entries_timestamp' => array(
        'type' => 'int',
        'description' => 'time().'
      )
    ),
    'primary key' => array('ip'),
  );
  db_create_table('cleantalk_sfw_logs', $cleantalk_sfw_logs);
  
  return '* New table for SpamFireWall logs added.';
}
