<?php
use Drupal\cleantalk\CleantalkSFW;
use Drupal\cleantalk\CleantalkCustomConfig;
use Drupal\cleantalk\CleantalkFuncs;

define("CLEANTALK_USER_AGENT", 'drupal-35');

/**
 * @file
 * Main CleanTalk integration module functions.
 */

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function cleantalk_form_alter(&$form, &$form_state, $form_id) 
{
  _cleantalk_form_alter($form, $form_state, $form_id);
}

/**
 * Cleantalk registration validation function.
 */
function cleantalk_validate_register(&$form, &$form_state) 
{
    if (variable_get('cleantalk_check_register', 0) && CleantalkFuncs::_cleantalk_check_form_submit_handlers($form_state['triggering_element']['#parents']))
    {
        $spam_check = array();

        $spam_check['type'] = 'register';
        $spam_check['sender_email'] = !empty($form_state['values']['mail']) ? $form_state['values']['mail'] : '';
        $spam_check['sender_nickname'] = !empty($form_state['values']['name']) ? $form_state['values']['name'] : '';
        $spam_check['timezone'] = !empty($form_state['values']['timezone']) ? $form_state['values']['timezone'] : '';

        $spam_result = CleantalkFuncs::_cleantalk_check_spam($spam_check);

        if (isset($spam_result) && is_array($spam_result) && $spam_result['errno'] == 0 && $spam_result['allow'] != 1) 
            form_set_error('mail', $spam_result['ct_result_comment']);        
    }
}

/**
 * Cleantalk comment validation function.
 */
function cleantalk_validate_comment(&$form, &$form_state) 
{
    if (variable_get('cleantalk_check_comments', 0) && CleantalkFuncs::_cleantalk_check_form_submit_handlers($form_state['triggering_element']['#parents']))
    {
        $spam_check = array();

        // Fill parameters array for usual comment
        $spam_check['type'] = 'comment';
        $comment_lang = array_key_exists('language', $form_state['values']) ? $form_state['values']['language'] : LANGUAGE_NONE;
        if (isset($form_state['values']['comment_body']) && is_array($form_state['values']['comment_body']) && isset($form_state['values']['comment_body'][$comment_lang]) && is_array($form_state['values']['comment_body'][$comment_lang]) && isset($form_state['values']['comment_body'][$comment_lang][0])) 
            $comment_body = $form_state['values']['comment_body'][$comment_lang][0];

        // Values below can be empty, we'll check as comment because of $base_form_id
        $spam_check['sender_email'] = !empty($form_state['values']['mail']) ? $form_state['values']['mail'] : '';
        $spam_check['sender_nickname'] = !empty($form_state['values']['name']) ? $form_state['values']['name'] : '';
        $spam_check['message_title'] = !empty($form_state['values']['subject']) ? $form_state['values']['subject'] : '';
        $spam_check['message_body'] = (is_array($comment_body) && isset($comment_body['value'])) ? $comment_body['value'] : ''; 

        $spam_result = CleantalkFuncs::_cleantalk_check_spam($spam_check);

        if (isset($spam_result) && is_array($spam_result) && $spam_result['errno'] == 0 && $spam_result['allow'] != 1)
        {
            if (variable_get('cleantalk_check_comments_automod', 0) == 0 || $spam_result['stop_queue'] == 1)
                form_set_error('comment_body', $spam_result['ct_result_comment']); 
        }                   
    }
}

/**
 * Cleantalk contact message validation function.
 */
function cleantalk_validate_contact_message(&$form, &$form_state) 
{
    if (variable_get('cleantalk_check_contact_forms',0) && CleantalkFuncs::_cleantalk_check_form_submit_handlers($form_state['triggering_element']['#parents']))
    {
        $spam_check = array();

        $spam_check['type'] = 'contact';
        $spam_check['sender_email'] = !empty($form_state['values']['mail']) ? $form_state['values']['mail'] : '';
        $spam_check['sender_nickname'] = !empty($form_state['values']['name']) ? $form_state['values']['name'] : '';
        $spam_check['message_title'] = !empty($form_state['values']['subject']) ? $form_state['values']['subject'] : '';
        $spam_check['message_body'] = !empty($form_state['values']['message']) ? $form_state['values']['message'] : '';

        $spam_result = CleantalkFuncs::_cleantalk_check_spam($spam_check);

        if (isset($spam_result) && is_array($spam_result) && $spam_result['errno'] == 0 && $spam_result['allow'] != 1) 
            form_set_error('comment_body', $spam_result['ct_result_comment']);        
    }
}

/**
 * Cleantalk webform validation function.
 */
function cleantalk_validate_webform(&$form, &$form_state) 
{
    if (variable_get('cleantalk_check_webforms',0) && CleantalkFuncs::_cleantalk_check_form_submit_handlers($form_state['triggering_element']['#parents']))
    {
        $spam_check = array();
        $ct_temp_msg_data = CleantalkFuncs::_cleantalk_get_fields_any($_POST);

        $spam_check['type'] = 'webform';
        if (empty($form_state['values']['submitted']['e_mail']))
            $spam_check['sender_email'] = ($ct_temp_msg_data['email']    ? $ct_temp_msg_data['email']    : '');
        else $spam_check['sender_email'] = $form_state['values']['submitted']['e_mail'];
        if (empty($form_state['values']['submitted']['name']))
            $spam_check['sender_nickname'] = ($ct_temp_msg_data['nickname']    ? $ct_temp_msg_data['nickname']    : '');
        else $spam_check['sender_nickname'] = $form_state['values']['submitted']['name'];        
        if (empty($form_state['values']['submitted']['subject']))
            $spam_check['message_title'] = ($ct_temp_msg_data['subject']    ? $ct_temp_msg_data['subject']    : '');
        else $spam_check['message_title'] = $form_state['values']['submitted']['subject'];  
        if (empty($form_state['values']['submitted']['message']))
            $spam_check['message_body'] = ($ct_temp_msg_data['message']    ? $ct_temp_msg_data['message']    : '');
        else $spam_check['message_body'] = $form_state['values']['submitted']['message'];             

        $spam_result = CleantalkFuncs::_cleantalk_check_spam($spam_check);
        if (isset($spam_result) && is_array($spam_result) && $spam_result['errno'] == 0 && $spam_result['allow'] != 1) 
            form_set_error('comment_body', $spam_result['ct_result_comment']);                                     
    }
}

/**
 * Implements hook_comment_presave().
 */
function cleantalk_comment_presave($comment) 
{
    $ct_result = CleantalkFuncs::_cleantalk_ct_result();

    if (!empty($ct_result['ct_request_id']))
    {
        if ($ct_result['ct_result_allow'] === 0 && variable_get('cleantalk_check_comments_automod', 0) === 1)
            $comment->status = COMMENT_NOT_PUBLISHED;
    }         
}
/**
 * Implements hook_menu().
 */
function cleantalk_menu() 
{
    $items['admin/config/cleantalk'] = array(
        'title' => 'Antispam by CleanTalk',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cleantalk_settings_form'),
        'access arguments' => array('administer site configuration'),
        'file' => 'lib/Drupal/cleantalk/Form/CleantalkSettingsForm.php',
    );

    $items['admin/config/cleantalk/settings'] = array(
        'title' => 'Settings',
        'description' => 'Configure module settings',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cleantalk_settings_form'),
        'access arguments' => array('administer site configuration'),
        'file' => 'lib/Drupal/cleantalk/Form/CleantalkSettingsForm.php',
    );    

    $items['admin/config/cleantalk/checkusers'] = array(
        'title' => 'Check users',
        'description' => 'Check existing spam users',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cleantalk_check_users_form'),
        'access arguments' => array('administer site configuration'),
        'file' => 'lib/Drupal/cleantalk/Form/CleantalkCheckUsersForm.php',
    );     

    $items['admin/config/cleantalk/checkcomments'] = array(
        'title' => 'Check comments',
        'description' => 'Check existing spam comments',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cleantalk_check_comments_form'),
        'access arguments' => array('administer site configuration'),
        'file' => 'lib/Drupal/cleantalk/Form/CleantalkCheckCommentsForm.php',
    );

    return $items;
}

/**
 * Cleantalk inner function - alters needed form.
 */
function _cleantalk_form_alter(&$form, &$form_state, $form_id) 
{
    $url_exclusion = CleantalkCustomConfig::get_url_exclusions();

    if ($url_exclusion)
    {
        foreach ($url_exclusion as $key=>$value)
            if (strpos($_SERVER['REQUEST_URI'],$value) !== false)
                return;         
    }   

    if (user_access('administer modules') && path_is_admin(current_path()) || $form_id == 'search_form' || $form_id =='user_login_form' || $form_id == 'search_block_form' || $form_id == 'user_login_block')
        return;

    if(variable_get('cleantalk_link', 0) != 0)
    {
        $form['terms_of_use'] = array(
        '#type' => 'item',
        '#markup' => t("<a href='https://cleantalk.org/drupal-anti-spam-module-wo-captcha'>Drupal spam</a> blocked by CleanTalk."),
        '#required' => FALSE,
        );
    }

    if ($form_id == 'user_register_form') 
        $form['#validate'][] = 'cleantalk_validate_register';    
    else 
    {
        if(preg_match('|comment(.*?)_form|', $form_id))
            $form['#validate'][] = 'cleantalk_validate_comment'; 
        if (preg_match('|contact(.*?)_form|', $form_id))     
            $form['#validate'][] = 'cleantalk_validate_contact_message';
        if (preg_match('|webform(.*?)_form|', $form_id))
            $form['#validate'][] = 'cleantalk_validate_webform';
    } 
}

/**
 * Implements hook_init()
 */

function cleantalk_init() 
{
    CleantalkFuncs::_cleantalk_apbct_cookies_set();

    $js_template = "var apbct_check_js_val = '%s';";
    $js_addon_body = sprintf($js_template, CleantalkFuncs::_cleantalk_get_checkjs_value());

    drupal_add_js($js_addon_body,
        array(
          'type' => 'inline',
          'scope' => 'header',
          'weight' => 5,
          'cache' => FALSE,
          'every_page' => TRUE,
        )
    ); 

    drupal_add_js(drupal_get_path('module', 'cleantalk') . '/lib/Drupal/cleantalk/js/apbct-public.js');

    $ct_authkey = trim(variable_get('cleantalk_authkey', ''));
    if($ct_authkey != '')
    {
        if(variable_get('cleantalk_sfw', 0))
        {
            $sfw = new CleantalkSFW();

            $ct_sfw_last_logs_sent = variable_get( 'ct_sfw_last_logs_sent', null);
            if($ct_sfw_last_logs_sent && (time() - $ct_sfw_last_logs_sent > 3600))
            {
                variable_set('ct_sfw_last_logs_sent', time());
                $sfw->send_logs($ct_authkey);
            }

            $ct_sfw_last_updated = variable_get( 'ct_sfw_last_updated', null);
            if($ct_sfw_last_updated && (time()-$ct_sfw_last_updated > 86400))
            {
                variable_set('ct_sfw_last_updated', time());
                $sfw->sfw_update($ct_authkey);
            }

            $is_sfw_check = true;

            $sfw->ip_array = (array)CleantalkSFW::ip_get(array('real'), true);  
                
            foreach($sfw->ip_array as $key => $value)
            {
                if(isset($_COOKIE['apbct_sfw_pass_key']) && $_COOKIE['apbct_sfw_pass_key'] == md5($value . $ct_authkey))
                {
                  $is_sfw_check=false;
                  if(isset($_COOKIE['apbct_sfw_passed']))
                  {
                    @setcookie ('apbct_sfw_passed'); //Deleting cookie
                    $sfw->sfw_update_logs($value, 'passed');
                  }
                }
            } unset($key, $value);  

            if($is_sfw_check)
            {
                $sfw->check_ip();
                if($sfw->result)
                {
                    $sfw->sfw_update_logs($sfw->blocked_ip, 'blocked');
                    $sfw->sfw_die($ct_authkey);
                }
            }
        }
        if(sizeof($_POST) > 0 && !isset($_POST['form_build_id']) && !isset($_POST['form_id']) && variable_get('cleantalk_ccf', 0)) //Custom Contact forms
        {
            $spam_check = array();
            $ct_temp_msg_data = CleantalkFuncs::_cleantalk_get_fields_any($_POST);

            $spam_check['type'] = 'custom_contact_form';

            $spam_check['sender_email'] = ($ct_temp_msg_data['email']    ? $ct_temp_msg_data['email']    : '');
            $spam_check['sender_nickname'] = ($ct_temp_msg_data['nickname']    ? $ct_temp_msg_data['nickname']    : '');       
            $spam_check['message_title'] = ($ct_temp_msg_data['subject']    ? $ct_temp_msg_data['subject']    : '');
            $spam_check['message_body'] = ($ct_temp_msg_data['message']    ? $ct_temp_msg_data['message']    : '');

            $spam_result = CleantalkFuncs::_cleantalk_check_spam($spam_check);

            if (isset($spam_result) && is_array($spam_result) && $spam_result['errno'] == 0 && $spam_result['allow'] != 1) 
                drupal_set_message($spam_result['ct_result_comment'],'error');     
        }
    }
}

/*
* implemments hook_uc_order - UberCart hook for order processing
*/

function cleantalk_uc_order($op, $order, $arg2) 
{
    $spam_check = array();
    $ct_temp_msg_data = CleantalkFuncs::_cleantalk_get_fields_any($_POST);

    $spam_check['type'] = 'custom_contact_form';

    $spam_check['sender_email'] = ($ct_temp_msg_data['email']    ? $ct_temp_msg_data['email']    : '');
    $spam_check['sender_nickname'] = ($ct_temp_msg_data['nickname']    ? $ct_temp_msg_data['nickname']    : '');       
    $spam_check['message_title'] = ($ct_temp_msg_data['subject']    ? $ct_temp_msg_data['subject']    : '');
    $spam_check['message_body'] = ($ct_temp_msg_data['message']    ? $ct_temp_msg_data['message']    : '');

    $spam_result = CleantalkFuncs::_cleantalk_check_spam($spam_check);

    if (isset($spam_result) && is_array($spam_result) && $spam_result['errno'] == 0 && $spam_result['allow'] != 1) 
    {
        if(strpos($_SERVER['REQUEST_URI'], 'ajax')!==false)
        {
            print $spam_result['ct_result_comment'];
            drupal_exit();
        } 
        else 
            _cleantalk_die($spam_result['ct_result_comment']);     
    }
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function cleantalk_form_user_filter_form_alter(&$form, &$form_state, $form_id) 
{
    $ct_authkey = variable_get('cleantalk_authkey', '');
    if (!empty($ct_authkey)) 
    {
        $form['actions']['find_spammers']  = array(
        '#type' => 'submit',
        '#value' => t('Check for spammers'),
        '#submit' => array('cleantalk_find_spammers'),
        );
    }
}

/**
 * Process submit of 'Check for spammers' button on user_filter_form.
 */
function cleantalk_find_spammers(&$form, &$form_state) 
{
    if (user_access('administer modules') && path_is_admin(current_path()))
    {
        $ct_authkey = variable_get('cleantalk_authkey', '');
        if (empty($ct_authkey)) 
            return;

        $op = $form_state['values']['op'];
        switch ($op) 
        {
            case t('Check for spammers'):
                // Load spammer role
                $spammer_role_name = 'spammer';
                $spammer_role = user_role_load_by_name($spammer_role_name);
                if ($spammer_role !== FALSE && is_object($spammer_role) && isset($spammer_role->rid)) 
                {
                    $is_spammer_defined = FALSE;
                    if (isset($_SESSION['user_overview_filter']) && is_array($_SESSION['user_overview_filter'])) 
                    {
                        foreach ($_SESSION['user_overview_filter'] as $filter)
                            if (is_array($filter) && isset($filter[0]) && $filter[0] == 'role' && isset($filter[1]) && $filter[1] == $spammer_role->rid) 
                                $is_spammer_defined = TRUE;
                    }
                    if (!$is_spammer_defined) 
                        $_SESSION['user_overview_filter'][] = array('role', $spammer_role->rid);
                

                    // Get all accounts
                    $accounts = user_load_multiple(FALSE);

                    // Fill data for spam check
                    $data = array();
                    foreach ($accounts as $account) 
                    {
                        // Skip adding the role to the user if they already have it.
                        if ($account !== FALSE && !isset($account->roles[$spammer_role->rid]) && isset($account->mail)) 
                            array_push($data, $account->mail);
                    }
                    $data=implode(',',$data);

                    $request=Array();
                    $request['method_name'] = 'spam_check_cms';
                    $request['auth_key'] = $ct_authkey;
                    $request['data'] = $data;
                    $url='https://api.cleantalk.org';
                    $result=CleantalkHelper::api_send_request($request);

                    $result=json_decode($result);

                    if(isset($result->error_message))
                        drupal_set_message($result->error_message,'error');
                    else
                    {
                        // Add roles for spam accounts
                        foreach ($accounts as $account) 
                        {
                            // Skip adding the role to the user if they already have it.
                            if ($account !== FALSE && !isset($account->roles[$spammer_role->rid]) && isset($account->mail)) 
                            {
                                $uim = $account->mail;
                                if(isset($result->data->$uim) && $result->data->$uim->appears==1)
                                {
                                    $roles = $account->roles + array($spammer_role->rid => $spammer_role_name);
                                    // For efficiency manually save the original account before applying
                                    // any changes.
                                    $account->original = clone $account;
                                    user_save($account, array('roles' => $roles));
                                }
                            }
                        }
                    }
                }
            break;
        }    
    }  
} 
